CFLAGS=     -O

.SUFFIXES: .o .c .s .exe

.c.o:
	$(CC) $(CFLAGS) -c $<

OFILES=     sst.o finish.o reports.o setup.o os2.o moving.o battle.o events.o ai.o planets.o

HFILES=     sst.h

sstos2.exe:  $(OFILES)
	gcc  -o sstos2.exe $(OFILES)

        
$(OFILES):  $(HFILES)

